name: Full Stack CI/CD Pipeline with Docker (No Tests)

on:
  push:
    branches:
      - Features
  pull_request:
    branches:
      - Features

jobs:
  # Frontend Job
  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Set a timeout to avoid indefinite running

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          # Install missing Babel dependency to suppress warnings
          npm install @babel/plugin-proposal-private-property-in-object --save-dev
      - name: Build frontend
        run: |
          cd frontend
          CI=false npm run build  # Suppresses warnings from failing the build in CI
  # Backend Job
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Set a timeout to avoid indefinite running

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      - name: Build backend
        run: |
          cd backend
          CI=false npm run build
  # Docker Job
  docker:
    runs-on: ubuntu-latest
    needs: 
      - backend
      - frontend # Ensure the backend job completes first
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tradezone:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tradezone:latest
